version: '3'

services:
  front:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/usr/app
    depends_on:
      - db
    networks:
      - my-network

  api:
    build: ./api
    command: yarn dev
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/app
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    networks:
      - my-network

networks:
  my-network:
