services:
  front:
    build: ./front
    ports:
      - "3006:3006"
    volumes:
      - ./front:/usr/app
    depends_on:
      - db
    network_mode: "host"
      
  api:
    build: ./api
    command: yarn dev
    ports:
      - "5000:5000"
    volumes:
      - ./api:/usr/app
    depends_on:
      - db
    network_mode: "host"
      
  db:
    image: postgres:latest
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: default
    volumes:
      - ./database/tables.sql:/docker-entrypoint-initdb.d/tables.sql

    ports:
      - "5432:5432"
    network_mode: "host"
